name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - uses: pnpm/action-setup@v4
        with:
          version: ^10.30.1

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint:client

      - name: Run audit
        run: pnpm audit --audit-level high

      - name: Run unit tests
        run: pnpm test:client:unit

      - name: Check if changeset is present
        if: github.actor != 'imodeljs-admin'
        run: |
          # There are issues with changesets in github workflows, so we need to force pull the master branch
          # Fix for issue https://github.com/changesets/changesets/issues/517#issuecomment-884778604
          git pull -f origin main:main
          pnpm changeset status --since=main
